platform: linux/arm

workspace:
  base: /go
  path: src/github.com/armswarm/drone-slack

clone:
  git:
    image: armswarmdrone/git

pipeline:
  build:
    image: quay.io/armswarm/golang:1.8-alpine
    environment:
      - CGO_ENABLED=0
      - PACKAGE=github.com/drone-plugins/drone-slack
    commands:
      - echo "${PACKAGE}"
      - go get -d "${PACKAGE}"
      - go vet "${PACKAGE}"
      - go test -cover -coverprofile=coverage.out "${PACKAGE}"
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo -o "${PACKAGE##*/}" "${PACKAGE}"

  publish:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/drone-slack
    tag: [ "1.0", "1", "latest" ]
    when:
      branch: master
      event: push

  notify:
    image: armswarmdrone/slack
    when:
      status: [ failure, success ]
